### ISSUE TITLE
upgrade php 8.1

### ISSUE THREAD

**Issue by domaingood** [bobbyiliev/laravel-digitalocean-1-click#1]
How can we upgrade php 8.1

**Comment by bobbyiliev** [comment]
You can just install the new version:

```bash
PHP="8.1"

sudo apt-get install -y php$PHP-cli php$PHP-common php$PHP-mysql php$PHP-gd php$PHP-mysql php$PHP-curl php$PHP-mbstring php$PHP-xml php$PHP-zip php$PHP-fpm

sudo rm /usr/bin/php
sudo ln -s /usr/bin/php$PHP /usr/bin/php
```

Then on line 24 in the Nginx config: `/etc/nginx/sites-available/laravel` change `php8.0-fpm.sock` to `php8.1-fpm.sock`. and after that restart Nginx: `systemctl restart nginx`.
