### ISSUE TITLE
Upgrade OS Ubuntu 22.04

### ISSUE THREAD

**Issue by domaingood** [bobbyiliev/laravel-digitalocean-1-click#2]
Please upgrade Upgrade OS Ubuntu 22.04
Defult PHP 8.1

**Comment by bobbyiliev** [comment]
Ubuntu 22.04 was released just a month or two ago. I will plan an upgrade in a couple few months once sure that there are no unexpected issues.

Ubuntu 20.04 is still going to be fully supported until April, 2025.

If you need to go for Ubuntu 22.04 straight away, I could suggest creating a plain Ubuntu 22.04 Droplet and following the steps here:

https://www.digitalocean.com/community/tutorials/how-to-install-and-configure-laravel-with-nginx-on-ubuntu-22-04

**Comment by bobbyiliev** [comment]
DigitalOcean announced that they will officially support Ubuntu 22.04 for their Marketplace apps just last month:

https://github.com/digitalocean/marketplace-partners

Will plan on upgrading the Laravel 1-Click soon.
